module.exports = {
  env: { browser: true, es2020: true },
  extends: [
    'airbnb',
    'eslint-config-prettier',
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:prettier/recommended",
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:prettier/recommended',
    'plugin:react/jsx-runtime',
    'plugin:react-hooks/recommended',
    'plugin:@tanstack/eslint-plugin-query/recommended',
  ],
  parserOptions: { ecmaVersion: 'latest', sourceType: 'module' },
  settings: { react: { version: '18.2' } },
  plugins: ['prettier', '@tanstack/query', 'react-refresh', 'waterfall'],
  rules: {
    '@tanstack/query/exhaustive-deps': 'error',
    '@tanstack/query/prefer-query-object-syntax': 'error',
    'react-refresh/only-export-components': 'off',
    'react/prop-types': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/button-has-type': 'off',
    'react/forbid-prop-types': 'off',
    'react/no-array-index-key': 'warn',
    'react/require-default-props': 'off',
    'react/jsx-filename-extension': 'error',
    'react/no-invalid-html-attribute': 'warn',
    'react/no-direct-mutation-state': 'error',
    'no-constant-condition': 'error',
    'jsx-a11y/anchor-is-valid': 'warn',
    'prefer-destructuring': 'off',
    'import/prefer-default-export': 'off',
    'dot-notation': 'error',
    'no-alert': 'error',
    'no-param-reassign': 'warn',
    'no-restricted-imports': [
      'error',
      {
        patterns: [
          {
            group: ['@/features/*/*'],
            message: "don't import form inside features.",
          },
        ],
      },
    ],
    'no-shadow': 'warn',
    'no-implied-eval': 'error',
    'no-return-await': 'error',
    'no-throw-literal': 'error',
    'no-nested-ternary': 'off',
    'consistent-return': 'warn',
    'import/order': 'off',
    // TODO: fix it for alias root
    'import/no-unresolved': 'off',
    '@next/next/no-img-element': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'jsx-a11y/no-noninteractive-element-interactions': 'off',
    'no-console': ['warn', { allow: ['warn', 'error'] }],
    'import/extensions': [
      'error',
      'ignorePackages',
      { '': 'never', js: 'never', jsx: 'never', ts: 'never', tsx: 'never' },
    ],
    'no-unused-vars': [
      'warn',
      {
        ignoreRestSiblings: false,
      },
    ],
    'no-unused-expressions': ['off', { allowShortCircuit: true }],
    'react/jsx-no-useless-fragment': [
      'error',
      {
        allowExpressions: true,
      },
    ],
    'react/jsx-props-no-spreading': [
      'error',
      {
        html: 'enforce',
        custom: 'ignore',
      },
    ],
    'waterfall/waterfall-imports': 'warn',
    'waterfall/waterfall-requires': 'warn',
  },
}
